import type { TemplateMeta } from "../../../templateTypes";

export const botanicalBabyShower: TemplateMeta = {
  id: "botanical-baby-shower",
  name: "Botanical Baby Shower",
  description: "An arched window with soft eucalyptus and fern growing in from the corners.",
  category: "baby-shower",
  alsoSuits: ["bridal-shower", "baptism"],
  styles: ["botanical", "romantic", "minimal"],
  layout: "arch-window",
  tier: "premium",
  status: "active",
  featured: true,
  addedAt: "2026-10-02",
  capabilities: {
    decorations: [
      { id: "branches", label: "Eucalyptus and fern" },
      { id: "bouquet", label: "Corner bouquet" },
    ],
    frames: ["arch-window", "oval", "double-line", "thin-line"],
    patterns: ["leaves"],
    backgrounds: ["wash-soft", "watercolor", "paper-grain"],
    backgroundImage: true,
    palettes: "any",
    fontPairings: ["garden", "romantic-script", "classic-serif", "geometric", "clean-grotesk"],
  },
  presets: [
    {
      id: "eucalyptus",
      name: "Eucalyptus",
      design: {
        headingFont: "Cormorant Garamond",
        bodyFont: "DM Sans",
        scriptFont: "Great Vibes",
        backgroundColor: "#E9EFEA",
        textColor: "#26362F",
        accentColor: "#5E7A6A",
        secondaryColor: "#B7C7B8",
        frame: { id: "arch-window" },
        decorations: ["branches"],
      },
    },
    {
      id: "blush-garden",
      name: "Blush Garden",
      design: {
        headingFont: "Cormorant Garamond",
        bodyFont: "DM Sans",
        backgroundColor: "#FBEFEC",
        textColor: "#4A3535",
        accentColor: "#B5736B",
        secondaryColor: "#D9A9A0",
        frame: { id: "arch-window" },
        background: { id: "wash-soft" },
        decorations: ["bouquet"],
      },
    },
    {
      id: "dusty-sky",
      name: "Dusty Sky",
      design: {
        headingFont: "Playfair Display",
        bodyFont: "Lora",
        backgroundColor: "#EAF0F2",
        textColor: "#1F2E3A",
        accentColor: "#4F6E8C",
        secondaryColor: "#A9C0D0",
        frame: { id: "double-line" },
        background: { id: "watercolor" },
        decorations: ["branches"],
      },
    },
  ],
  sampleContent: {
    eventTitle: "A baby shower for",
    hostNames: "Nina & Sam",
    date: "2026-05-16",
    time: "14:00",
    venue: "The Sunroom",
    address: "7 Greenhouse Row",
    message: "Join us for tea, cake and a little bit of love.",
  },
};
