import type { TemplateMeta } from "../../../templateTypes";

export const vintageBirthday: TemplateMeta = {
  id: "vintage-birthday",
  name: "Vintage Birthday",
  description: "An old-fashioned poster with a wreath, a fat display name and a ribbon banner.",
  category: "birthday",
  alsoSuits: ["anniversary", "retirement", "dinner-party"],
  styles: ["vintage", "traditional"],
  layout: "badge-seal",
  tier: "premium",
  status: "active",
  addedAt: "2026-10-01",
  capabilities: {
    decorations: [
      { id: "laurel", label: "Laurel wreath" },
      { id: "corners", label: "Corner flourishes" },
      { id: "seal", label: "Seal" },
    ],
    frames: ["double-line", "notched-corners", "oval", "thin-line"],
    patterns: ["diamonds", "deco-fans", "stripes"],
    backgrounds: ["paper-grain", "vignette", "linen"],
    backgroundImage: true,
    palettes: "any",
    fontPairings: ["fat-display", "poster-serif", "engraved", "deco-display", "classic-serif"],
  },
  presets: [
    {
      id: "parchment",
      name: "Parchment",
      design: {
        headingFont: "Abril Fatface",
        bodyFont: "Lora",
        backgroundColor: "#F1E6CF",
        textColor: "#2F2A22",
        accentColor: "#8B3A2F",
        secondaryColor: "#2F4A58",
        frame: { id: "double-line" },
        background: { id: "paper-grain" },
        decorations: ["laurel", "seal"],
      },
    },
    {
      id: "navy-cream",
      name: "Navy & Cream",
      design: {
        headingFont: "DM Serif Display",
        bodyFont: "DM Sans",
        backgroundColor: "#F4F1EA",
        textColor: "#1F2A44",
        accentColor: "#7A1F2B",
        secondaryColor: "#B79B5A",
        frame: { id: "notched-corners" },
        background: { id: "vignette" },
        decorations: ["laurel", "corners"],
      },
    },
    {
      id: "kraft",
      name: "Kraft",
      design: {
        headingFont: "Abril Fatface",
        bodyFont: "Lora",
        backgroundColor: "#EDE3D2",
        textColor: "#43352A",
        accentColor: "#9A6B3F",
        secondaryColor: "#6F7B4D",
        frame: { id: "thin-line" },
        pattern: { id: "stripes", opacity: 0.08 },
        background: { id: "linen" },
        decorations: ["seal"],
      },
    },
  ],
  sampleContent: {
    eventTitle: "Turns Fifty",
    hostNames: "Harold",
    date: "2026-11-07",
    time: "19:00",
    venue: "The Old Mill",
    address: "14 Mill Lane",
    message: "An evening of good food, better company and a few embarrassing stories.",
  },
};
