import type { TemplateMeta } from "../../../templateTypes";

export const luxuryWedding: TemplateMeta = {
  id: "luxury-wedding",
  name: "Luxury Wedding",
  description: "Wide-tracked capitals, a foil monogram seal and fine double rules.",
  category: "wedding",
  styles: ["luxury", "elegant"],
  layout: "framed-card",
  tier: "premium",
  status: "active",
  featured: true,
  addedAt: "2026-10-01",
  capabilities: {
    decorations: [
      { id: "monogram", label: "Monogram seal" },
      { id: "divider", label: "Diamond divider" },
      { id: "corners", label: "Corner flourishes" },
    ],
    frames: ["foil-double", "notched-corners", "double-line", "thin-line"],
    patterns: ["deco-fans", "diamonds"],
    backgrounds: ["foil-sheen", "vignette", "wash-soft", "paper-grain"],
    backgroundImage: true,
    palettes: "any",
    fontPairings: ["luxe-caps", "deco-display", "fashion-serif", "classic-serif", "engraved"],
  },
  presets: [
    {
      id: "black-gold",
      name: "Black & Gold",
      design: {
        headingFont: "Cinzel",
        bodyFont: "Montserrat",
        backgroundColor: "#14161C",
        textColor: "#F2EDE4",
        accentColor: "#C8A96A",
        secondaryColor: "#8C7A4E",
        frame: { id: "foil-double" },
        background: { id: "foil-sheen" },
        decorations: ["monogram", "divider"],
      },
    },
    {
      id: "ivory-foil",
      name: "Ivory Foil",
      design: {
        headingFont: "Italiana",
        bodyFont: "DM Sans",
        backgroundColor: "#F6F1E8",
        textColor: "#2E2A24",
        accentColor: "#8A7352",
        secondaryColor: "#C8A96A",
        frame: { id: "notched-corners" },
        pattern: { id: "deco-fans", opacity: 0.12 },
        decorations: ["monogram", "corners"],
      },
    },
    {
      id: "emerald-deco",
      name: "Emerald Deco",
      design: {
        headingFont: "Cinzel",
        bodyFont: "Montserrat",
        backgroundColor: "#12302A",
        textColor: "#EEF0E8",
        accentColor: "#C8A96A",
        secondaryColor: "#8C7A4E",
        frame: { id: "double-line" },
        pattern: { id: "diamonds", opacity: 0.16 },
        background: { id: "vignette" },
        decorations: ["monogram", "divider", "corners"],
      },
    },
  ],
  sampleContent: {
    eventTitle: "The wedding of",
    hostNames: "Isabella & Alexander",
    date: "2026-12-12",
    time: "17:30",
    venue: "The Grand Ballroom",
    address: "1 Royal Crescent",
    message: "Black tie. Dinner and dancing to follow.",
  },
};
