import { allTemplates } from "../src/components/invitation/templateCatalog";

/**
 * The SQL that mirrors the catalog's Free/Premium facts into the `templates` table, where the database uses them
 * to enforce Premium access. The catalog stays the source of truth: when it changes, run
 * `npm run templates:sql -- <name>` to write a new migration. `npm run check:templates` fails if the newest
 * mirror migration no longer matches the catalog.
 */
export const MIRROR_HEADER = "-- Generated by `npm run templates:sql`. Mirrors the app's template catalog (Free/Premium). Safe to re-run.";

const quote = (s: string) => `'${s.replace(/'/g, "''")}'`;

export function generateTemplatesSql(): string {
  const rows = allTemplates().map((t) => {
    const premiumLooks = t.presets.filter((p) => p.tier === "premium").map((p) => p.id);
    const configuration = JSON.stringify({ premiumPresets: premiumLooks });
    return `  (${quote(t.name)}, ${quote(t.id)}, ${quote(t.category)}, ${t.tier === "premium"}, ${quote(configuration)}::jsonb)`;
  });
  return `${MIRROR_HEADER}

insert into public.templates (name, slug, category, is_premium, configuration)
values
${rows.join(",\n")}
on conflict (slug) do update
  set name = excluded.name,
      category = excluded.category,
      is_premium = excluded.is_premium,
      configuration = public.templates.configuration || excluded.configuration;
`;
}

if (process.argv[1]?.endsWith("templatesSql.ts")) {
  const name = process.argv[2];
  const sql = generateTemplatesSql();
  if (!name) process.stdout.write(sql);
  else {
    const { writeFileSync } = await import("node:fs");
    const stamp = new Date().toISOString().replace(/\D/g, "").slice(0, 14);
    const file = `supabase/migrations/${stamp}_templates_mirror_${name}.sql`;
    writeFileSync(file, sql);
    console.log(`wrote ${file}`);
  }
}
